import React from 'react';
import {Col, Collapse, Row} from 'antd';
import { NavLink } from "react-router-dom";

const { Panel } = Collapse;

const HowItWorks = () => {
    return (
        <Collapse className="howITworks" accordion>
            <Panel header="How does it work?" key="1">
                <Row gutter={24}>
                    <Col span={24} sm={24} xs={24} md={12}>
                        <h3>
                            This prototype incorporates a full insurance with one nameless insurance product, for an imaginary peril.
                            We don't care about the details, the only thing we need to know is that the "sum insured" is 200x the premium.
                            Therefore, if you pay $150 in premium, you are insured for $30,000.
                        </h3>
                        <h3>
                            But before a customer can purchase an insurance, somebody has to provide capacity.
                            The provision of capacity takes place in two steps.
                        </h3>
                        <h3>

                            In the <span style={{color: '#00A99D',}}>first step</span>, an investor deposits DIP tokens in the "Secondary Risk Pool".
                            In return, he receives "Risk Pool Tokens" (RPT). Later, he can trade those RPT
                            or sell them back to the Secondary Risk Pool (provided the pool has enough DIP left.
                        </h3>
                    </Col>
                    <Col span={24} sm={24} xs={24} md={12}>

                        <h3>
                            In the <span style={{color: '#00A99D',}}>second step</span>, the <NavLink to="/riskpool/secondary">Secondary Risk Pool</NavLink> - which could be governed by a DAO, or a Risk Pool Keeper,
                            deposits the DIP in the <NavLink to="/riskpool/primary">Primary Risk Pool</NavLink>.
                            In return, the Secondary Risk Pool receives an NFT. The NFT represents all policies which are sold until the NFT is "terminated".
                        </h3>
                        <h3>

                            Because of the volatility, the DIP tokens which are deposited in the Primary Risk Pool cannot be fully used as capacity.
                            The factor which determines the share of the DIP which can be used as capacity is called "MCR" from "Minimum Capital Requirement".
                            In our example, the factor is 0.8 or 80%.
                        </h3>
                        <h3>

                            As soon as the NFT is minted, the capacitiy is provided to the product and policies can be purchased.
                            Each policy purchased reduces the capacity until the capacity is either 0 or new capacity is generated by minting of new NFTs.
                        </h3>
                    </Col>
                </Row>


            </Panel>
        </Collapse>
    )
}

export default HowItWorks;
